manifest:
  remotes:
    - name: zmkfirmware
      # url-base: https://github.com/zmkfirmware
      # url-base: https://github.com/infused-kim/
      url-base: https://github.com/rluna319
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config